In [1]:
import numpy as np

# Sample data matrix (m samples, n features)
X = np.array([[0.96, 1.72, 1.92], [1.72, 0.96, 3.55], [1.92, 3.55, 3.84]])

# Step 1: Center the data
X_centered = X - np.mean(X, axis=0)

# Step 2: Compute covariance matrix
cov_matrix = np.cov(X_centered, rowvar=False)

# Step 3: Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Step 4: Sort eigenvectors by descending eigenvalues
idx = np.argsort(eigenvalues)[::-1]
principal_components = eigenvectors[:, idx]

print("Principal Components:\n", principal_components)

Principal Components:
 [[-0.25952897  0.34437059 -0.90224919]
 [-0.82462689 -0.56527024  0.02144876]
 [-0.5026283   0.74958552  0.43068125]]
